<a href="https://colab.research.google.com/github/srujaan/ubiquitous-enigma/blob/master/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3],dtype='int32')
a

array([1, 2, 3], dtype=int32)

In [3]:
b = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [4]:
# get dimension
b.ndim

2

In [5]:
# get shape
b.shape

(2, 6)

In [6]:
a.shape

(3,)

In [7]:
# get size
b.itemsize

8

In [8]:
# get total size
b.nbytes

96

In [9]:
a.nbytes

12

In [10]:
# get number of elements
a.size

3

### Accessing/Changing specific elements, rows, columns, etc

In [11]:
a = np.array([[1,2,3,4,5,6,7,8], [9,10,11,12,13,14,15,16]])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])

In [12]:
a.shape, a.size, a.ndim

((2, 8), 16, 2)

In [13]:
# get a specific element [r, c]
a[0, 5]

6

In [14]:
a[1,-2]

15

In [15]:
# get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
# get a specific column
a[:, 1]

array([ 2, 10])

In [17]:
a[:, 3], a[:, 5]

(array([ 4, 12]), array([ 6, 14]))

In [18]:
a[1, 4]

13

In [19]:
# getting a little more fancy [startindex:endindex:stepsize]
a[:, 1:-1: 2]

array([[ 2,  4,  6],
       [10, 12, 14]])

In [20]:
a[1, :-1: 2]

array([ 9, 11, 13, 15])

In [21]:
a[:, 1:4: 1]

array([[ 2,  3,  4],
       [10, 11, 12]])

In [22]:
# get a specific column
a[:, 2]

array([ 3, 11])

In [23]:
a[1,5] = 20

In [24]:
a


array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 20, 15, 16]])

In [25]:
a[:, 3] = [99, 88]
print(a)

[[ 1  2  3 99  5  6  7  8]
 [ 9 10 11 88 13 20 15 16]]


3-D array example

In [26]:
b = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [27]:
b.shape, b.size, b.ndim

((1, 4, 2), 8, 3)

In [28]:
# get specific element (work outside in)
b[0,3,1]

8

In [29]:
# replace
b[:,1,:] = [9,9]
b

array([[[1, 2],
        [9, 9],
        [5, 6],
        [7, 8]]])

### Initialize Different Types of Arrays

In [30]:
# All 0s matrix
z = np.zeros((2,2))
z

array([[0., 0.],
       [0., 0.]])

In [31]:
z.shape, z.ndim, z.size

((2, 2), 2, 4)

In [32]:
# All 1s matrix
o = np.ones((1,6),dtype='int32')
o

array([[1, 1, 1, 1, 1, 1]], dtype=int32)

In [33]:
o.shape, o.ndim, o.size

((1, 6), 2, 6)

In [34]:
# Any other full
f = np.full((2,2),7,'int32')
f

array([[7, 7],
       [7, 7]], dtype=int32)

In [35]:
# Random decimal numbers
np.random.rand(2,3)

array([[0.04869332, 0.21358974, 0.05442651],
       [0.77134141, 0.22275197, 0.92885813]])

In [36]:
# Random integer value
np.random.randint(-2,8,size=(2,3))

array([[-1,  0,  5],
       [ 5, -1,  2]])

In [37]:
# The identity matrix
np.eye(3,dtype='int32')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [38]:
op = np.ones((6,6), dtype='int32')
op

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [39]:
op[1:-1, 1:-1] = 9

In [40]:
op[2:4, 2:4] = [0,0]
op

array([[1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 1],
       [1, 9, 0, 0, 9, 1],
       [1, 9, 0, 0, 9, 1],
       [1, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [41]:
op[2:4, 2:4] = np.identity(2,dtype='int32')

In [42]:
op[2:4, 2:4]

array([[1, 0],
       [0, 1]], dtype=int32)

In [43]:
op

array([[1, 1, 1, 1, 1, 1],
       [1, 9, 9, 9, 9, 1],
       [1, 9, 1, 0, 9, 1],
       [1, 9, 0, 1, 9, 1],
       [1, 9, 9, 9, 9, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

### Linear Algebra

In [44]:
a = np.ones((4,7))
print(a, a.shape, a.size)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]] (4, 7) 28


In [45]:
b = np.full((7,6),9)
print(b, b.shape, b.size)

[[9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]
 [9 9 9 9 9 9]] (7, 6) 42


In [46]:
c =np.matmul(a,b)
print(c, c.shape, c.size)

[[63. 63. 63. 63. 63. 63.]
 [63. 63. 63. 63. 63. 63.]
 [63. 63. 63. 63. 63. 63.]
 [63. 63. 63. 63. 63. 63.]] (4, 6) 24


### Reorganizing Arrays

In [47]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before, before.shape)
print(before.T, before.T.shape)


[[1 2 3 4]
 [5 6 7 8]] (2, 4)
[[1 5]
 [2 6]
 [3 7]
 [4 8]] (4, 2)


In [48]:
after = np.reshape(before, newshape=(4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
np.arange(3)

array([0, 1, 2])

In [50]:
np.arange(2,9,2)

array([2, 4, 6, 8])

You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. Note that this is quite different from the way that MATLAB handles array slicing:

In [51]:
# create the rank 2 array with shape (3,4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a, a.shape

(array([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]), (3, 4))

In [52]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:

In [53]:
row_r1 = a[1, :] # Rank 1 view of the second row of a
row_r1, row_r1.shape # Prints "[5 6 7 8] (4,)

(array([5, 6, 7, 8]), (4,))

In [54]:
row_r2 = a[1:2, :] # Rank 2 view of the second row of a
row_r2, row_r2.shape # # Prints "[[5 6 7 8]] (1, 4)

(array([[5, 6, 7, 8]]), (1, 4))

### We can make the same distinction when accessing columns of

In [55]:
col_c1 = a[:, 2] # Rank 1 view of the third col of a
col_c1, col_c1.shape # prints "[3,7,11]" (3,)

(array([ 3,  7, 11]), (3,))

In [56]:
col_c2 = a[:, 2:3]  # Rank 2 view of the third col of a
col_c2, col_c2.shape # prints [[3], [7], [11]], (3,1)

(array([[ 3],
        [ 7],
        [11]]), (3, 1))

# Integer array indexing

#### When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example

In [57]:
a2 = np.array([[1,2], [3,4], [5,6]])

# An example of integer array indexing.
# The returned array will have shape (3,) and

r = (a2[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]
print(r, r.shape)

[1 4 5] (3,)


In [58]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a2[0,0], a2[1,1], a2[2,0]]))

[1 4 5]


In [59]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a2[[0,0], [1,1]]) # prints [2,2]

[2 2]


In [60]:
# Equivalent to the previous integer array indexing example
print(np.array([a2[0,1], a2[0,1]]))  # prints[2,2]

[2 2]


### One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [61]:
# Create a new array from which we will select elements

a3 = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a3)

# create an array of indices
b = np.array([0, 2, 0, 1])
b

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


array([0, 2, 0, 1])

In [62]:
# Select one element from each row of a using the indices in b
print(a3[np.arange(4), b])

[ 1  6  7 11]


In [63]:
# Mutate one element from each row of a using the indices in b
a3[np.arange(4), b] += 10
print(a3)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [64]:
c = np.array([2, 1, 0, 1])
print(c)

[2 1 0 1]


In [65]:
a3[np.arange(4), c] += 100
print(a3)

[[ 11   2 103]
 [  4 105  16]
 [117   8   9]
 [ 10 121  12]]


# Boolean array indexing:

#### Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [66]:
a4 = np.array([[1,2], [3,4], [5,6], [7, 8]])
bool_idx = (a4 > 2) # Find the elements of a that are bigger than 2;
                     # this returns a numpy array of Booleans of the same
                     # shape as a, where each slot of bool_idx tells
                     # whether that element of a is > 2

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]
 [ True  True]]


In [67]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx

print(a4[bool_idx])

[3 4 5 6 7 8]


In [68]:
# We can do all of the above in a single concise statement:
print(a4[a4 > 2])

[3 4 5 6 7 8]


# Array math

#### Note that unlike MATLAB, * is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [69]:
x = np.array([[1,2], [3,4]])
y = np.array([[5,6], [7,8]])


v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))

219


In [70]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [71]:
# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x,y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [73]:
print(np.sum(x)) # # Compute sum of all elements; prints "10"

10


In [75]:
print(np.sum(x, axis=0))  #  # Compute sum of each column; prints "[4 6]"

[4 6]


In [77]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[3 7]


#### Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [79]:
print(x, x.shape)

[[1 2]
 [3 4]] (2, 2)


In [80]:
print(x.T, x.T.shape)

[[1 3]
 [2 4]] (2, 2)


In [81]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)
print(v.T)

[1 2 3]
[1 2 3]


# Broadcasting

#### Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

#### For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [86]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])

y = np.empty_like(x) # # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop

for i in range(4):
  y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#### This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector `v` to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [93]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y

x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])

vv = np.tile(v, (4,1)) # Stack 4 copies of v on top of each other
print(vv) # Prints "[[1 0 1]
          #          [1 0 1]
          #          [1 0 1]
          #          [1 0 1]]"
y = x + vv
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
